version: '3'

services:
  fadocs:
    build: .
    image: gcr.io/racoo-248604/fadocs
    restart: unless-stopped
    environment:
      COMPOSER_MEMORY_LIMT: -1
      COMPOSER_PROCESS_TIMEOUT: 2000
    expose:
      - 80
    ports:
      - 8083:80
